<?php

namespace ShopBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * SalesOrderProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesOrderProductRepository extends EntityRepository
{
}
