<?php

namespace ShopBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * SalesOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesOrderRepository extends EntityRepository
{
	/*
	 * Uses : AnalyticsController::indexAction
	 */
	public function getOrdersInformation($dateStart, $dateEnd)
    {
		$qb1 = $this->createQueryBuilder('s')
				   ->select('COUNT(s)')
				   ->where('s.creationDate >= :today1')->setParameter('today1', $dateStart.' 00:00:00')
				   ->andWhere('s.creationDate <= :today2')->setParameter('today2', $dateEnd.' 23:59:59');
		
		$qb2 = $this->createQueryBuilder('s')
				   ->select('SUM(sop.quantity * sop.price)')
				   ->leftJoin('s.salesOrderProducts', 'sop')
				   ->where('s.creationDate >= :today1')->setParameter('today1', $dateStart.' 00:00:00')
				   ->andWhere('s.creationDate <= :today2')->setParameter('today2', $dateEnd.' 23:59:59');

		return array(
			'nbr' => $qb1->getQuery()->getSingleScalarResult(),
			'amt' => $qb2->getQuery()->getSingleScalarResult()
		);
    }
}
