imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed_error
        streamed_error:
            type:           rotating_file
            max_files:      15
            path:           %kernel.logs_dir%/%kernel.environment%.error.log
            level:          info

        main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        grouped_critical
        grouped_critical:
            type:           group
            members:        [streamed_critical, buffered_critical]
        streamed_critical:
            type:           rotating_file
            max_files:      15
            path:           %kernel.logs_dir%/%kernel.environment%.critical.log
            level:          info
        buffered_critical:
            type:           buffer
            handler:        swift_critical
        swift_critical:
            type:           swift_mailer
            from_email:     %mailer_sender%
            to_email:       %mailer_admin%
            subject:        "[GSD] Erreurs Symfony"
            level:          info

# SalesforceBundle Configuration
salesforce:
    authentication:
        endpoint: 'https://login.salesforce.com/'
        client_id: '3MVG9TSaZ8P6zP1q9_Jifod1L4GSr8KDT5ZSlmHE7ENPoOytqhYy_Sg8fA9GuA7WKj0SDrb1p6QGxSU8aJOnU'
        client_secret: '2620795736996676035'
        username: 'svc-salesforce@sasa-demarle.com'
        password: '5xWi2p4pAe68cVAAvV75'
        security_token: 'UAswUiObPV2FfdTae0tBuQJF'
    rest:
        version: 'v43.0'
        endpoint: 'https://eu8.salesforce.com'
