<?php

namespace ContactUsBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
	/*
	 * Uses : AnalyticsController::indexAction
	 */
	public function getContactsAmount($dateStart, $dateEnd)
    {
		$qb = $this->createQueryBuilder('c')
				   ->select('COUNT(c)')
				   ->where('c.creationDate >= :today1')->setParameter('today1', $dateStart.' 00:00:00')
				   ->andWhere('c.creationDate <= :today2')->setParameter('today2', $dateEnd.' 23:59:59');

		return $qb->getQuery()->getSingleScalarResult();
    }
}
