<?php

namespace ContactUsBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * EmailingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailingRepository extends EntityRepository
{
	/*
	 * Uses : PublicController::index
	 */
	public function getRecipient($productType, $france)
	{
		$qb = $this->createQueryBuilder('e')
				   ->where('e.productType = ?1')->setParameter(1, $productType)
				   ->andWhere('e.france = ?2')->setParameter(2, $france);
		
		return $qb->getQuery()->getResult();
	}
}
