<?php

namespace ContactUsBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * PurposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurposeRepository extends EntityRepository
{
}
