<?php

namespace BonusBundle\Repository;

use \Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Types\Type as DoctrineType;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
	/*
	 * Uses : PublicController::eventAction
	 */
	public function getOpenedEvents()
	{
		$qb = $this->createQueryBuilder('e')
				   ->where('e.endDate >= :endDate')->setParameter('endDate', new \DateTime('now'), DoctrineType::DATE)
				   ->orderBy('e.startDate', 'asc');

		return $qb->getQuery()->getResult();
	}
}
