<?php

namespace BonusBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * TechnicalNoticeCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicalNoticeCategoryRepository extends EntityRepository
{
}
